function [peaks, locs, width]=FindPeaks(Line)
% findpeak on vertical line scan, with wavelet denoising
C = wdenoise(double(Line),1, ...
    'Wavelet', 'sym4', ...
    'DenoisingMethod', 'Bayes', ...
    'ThresholdRule', 'Median', ...
    'NoiseEstimate', 'LevelIndependent');
[peaks, locs, width] = findpeaks(C, 'MinPeakHeight', 0.35*max(C), ...
    'MinPeakWidth', 1.5, 'MinPeakDistance', 6, 'MinPeakProminence', 2);
end